<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE PORTFOLIO [
<!ENTITY AUTOR "Stanislav Siviskiy" >
<!ELEMENT NAME (#PCDATA) >
<!ELEMENT PHOTO (#PCDATA) >
<!ATTLIST PHOTO
SRC CDATA #REQUIRED
WIDTH CDATA #IMPLIED
HEIGHT CDATA #IMPLIED>
<!ELEMENT DATE (#PCDATA) >
<!ELEMENT EMAIL (#PCDATA) >
<!ELEMENT PHONE (#PCDATA) >
<!ELEMENT HOBBY (#PCDATA) >
<!ELEMENT CONTENT (NAME, DATE?, EMAIL?, PHONE?, HOBBY?) >
<!ELEMENT STUDENT (PHOTO?, CONTENT) >
<!ATTLIST STUDENT 
   ID	CDATA	#REQUIRED >
<!ELEMENT PORTFOLIO (STUDENT+) >
]>
<?xml-stylesheet href="lang.css" type="text/css"?>
<PORTFOLIO>
		<STUDENT ID="1">
			<PHOTO SRC="http://www.welcomespb.com/images/foto-rabota2big01.jpg" WIDTH="150px"></PHOTO>
			<CONTENT>
			<NAME>Вася Пупкин</NAME>
			<DATE>00.00.0000</DATE>
			<EMAIL>pupkin@mail.ru</EMAIL>
			<PHONE>8-888-888-88-88</PHONE>
			<HOBBY>
			Увлекается программированием, учебой, чтением на латинском
			</HOBBY>
			</CONTENT>
		</STUDENT>
		<STUDENT ID="2">
			<PHOTO SRC="http://previews.123rf.com/images/auremar/auremar1211/auremar121103263/16472186-student-swamped-under-work-Stock-Photo.jpg" WIDTH="150px"></PHOTO>
			<CONTENT>
			<NAME>Гена Ака Ботаник Зубрилов</NAME>
			<DATE>11.12.1992</DATE>
			<EMAIL>ucheba@mail.ru</EMAIL>
			<PHONE>8-777-666-66-66</PHONE>
			<HOBBY>
			Любит астрономию, биологию и биоинформатику. Играет на гитаре.
			</HOBBY>
			</CONTENT>
		</STUDENT>
		<STUDENT ID="3">
			<PHOTO SRC="https://wallpaperscraft.ru/image/biblioteka_student_devushka_uchebniki_77146_602x339.jpg" WIDTH="150px"></PHOTO>
			<CONTENT>
			<NAME>Анжелика Султанова</NAME>
			<DATE>25.04.1991</DATE>
			<EMAIL>lika_pupsik@mail.ru</EMAIL>
			<PHONE>8-747-789-54-90</PHONE>
			<HOBBY>
			Заядлая троешница и прогульщица пар. Курит. Состояла в детской комнате милиции.
			</HOBBY>
			</CONTENT>
		</STUDENT>
		<STUDENT ID="4">
			<PHOTO SRC="https://i.onthe.io/pogudxmm8mgued6lg.03b4bf6a.jpg" WIDTH="150px"></PHOTO>
			<CONTENT>
			<NAME>Баке</NAME>
			<DATE>25.08.1990</DATE>
			<EMAIL>opasniy_gansta@gmail.com</EMAIL>
			<PHONE>8-111-777-00-00</PHONE>
			<HOBBY>
			Сын ректора. О нем или хорошо или ничего.
			</HOBBY>
			</CONTENT>
		</STUDENT>
		<STUDENT ID="4">
			<PHOTO SRC="http://www.dw.com/image/16912354_303.jpg" WIDTH="150px"></PHOTO>
			<CONTENT>
			<NAME>Студент обыкновенный</NAME>
			<DATE>25.08.1990</DATE>
			<EMAIL>studentota@gmail.com</EMAIL>
			<PHONE>8-111-777-00-00</PHONE>
			<HOBBY>
			Обычный студент. Любит спать, играть и прогуливать пары.
			</HOBBY>
			</CONTENT>
		</STUDENT>
		&AUTOR;
	</PORTFOLIO>